### ISSUE TITLE
Documentation on website is for RC, not the release version distributed with npm install

### ISSUE THREAD

**Issue by confusingbits** [immutable-js/immutable-js#1380]
And there doesn't appear to be any links to the actual release version docs on the website.

I appreciate this library and the work that goes into it, but this was very confusing.

I would propose that the website should show the release version docs by default, and have links to other versions where applicable.

Or at the very least, a link to the release docs somewhere on the main page.

For example:

Bootstrap has a drop down for other versions even if they show a pre-release version by default: http://getbootstrap.com/
Express docs show release and have a drop down for versions: https://expressjs.com/
Django shows release, and has a button to switch between versions in the docs: https://docs.djangoproject.com/en/1.11/
.Net shows latest release and has a drop down for other versions: https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7

**Comment by leebyron** [comment]
I won't have time to do this, but if anyone would like to work on this I'd be happy to review PRs

**Comment by b4lk0n** [comment]
@leebyron so it's okay that package version on npm is 3.x.x and website link leads to 4.x.x docs? )

**Comment by darrencrossley** [comment]
Are the release version 3.x docs available anywhere?

**Comment by Ceasar** [comment]
I found the latest 3.x docs on Wayback machine here: https://web.archive.org/web/20170301035953/https://facebook.github.io/immutable-js/docs/#/
