### ISSUE TITLE
Type incompatibility issues with groupBy()

### ISSUE THREAD

**Issue by omninonsense** [immutable-js/immutable-js#1412]
### What happened

It seems that certain functions' typedefs return types that conflict with the return type. The example below might illustrate what I mean better.

I haven't looked at the type defs too closely, but I imagine this could be simplified somehow?

### How to reproduce

~~~js
// @flow

import { Map, List } from 'immutable'

const l = List([1,2,3,4,5,6,7])
const m : Map<string, List<number>> = l.groupBy((e) => e % 2 === 0 ? 'even' : 'odd')
~~~

which generates the following flow error:

~~~
  6: const m : Map<string, List<number>> = l.groupBy((e) => e % 2 === 0 ? 'even' : 'odd')
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyedSeq. This type is incompatible with
  6: const m : Map<string, List<number>> = l.groupBy((e) => e % 2 === 0 ? 'even' : 'odd')
               ^^^^^^^^^^^^^^^^^^^^^^^^^ Map
~~~

The workaround I have found is to simply wrap the whole thing in a call to `Map(l.groupBy…)`, which seems to make flow happy:

~~~js
// @flow

import { Map, List } from 'immutable'

const l = List([1,2,3,4,5,6,7])
const m : Map<string, List<number>> = Map(l.groupBy((e) => e % 2 === 0 ? 'even' : 'odd'))
~~~

However, I am not sure if this is the intended way to use this. Am I being stupid here?

P.S: I understand that technically `groupBy` returns an `OrderedMap` (I tried to use that type too, with same error message regarding type incompatibility).

**Comment by leebyron** [comment]
This is a currently a real type incompatibility in your program and your fix was the correct one. A KeyedSeq cannot be assigned to a Map, but `Map()` will do the correct coercion.

While the currently implementation detail is groupBy() returns an OrderedMap, this is something that was thought could change in the future to a lazy operation, but that may be worth a revisit. I'll investigate
