### ISSUE TITLE
Give `set` and `setIn` methods names which match their function more clearly

### ISSUE THREAD

**Issue by toni-sharpe** [immutable-js/immutable-js#1425]
I'd like to suggest that the `set` and `setIn` and methods are renamed to something more intuitive, a better reflection of what the method actually does.

With `get` (and `getIn`) the method operates directly on the Immutable object and returns a value, which is implied by the way the code is written. The operation takes place on the object and a value is returned and this maps very nicely onto our mental understanding of how the world works.

With `set`  (and `setIn`) the same implication is given. We think we are operating an object and setting something within it but this doesn't reflect what is actually happening with Immutable (which is that a new object is returned with the value set in it).

I see this come up quite frequently where a developer has forgotten they have to get the returned value from `set` and assign it to a new variable. While I understand this is fundamental to how Immutable data works I feel the method name obscures this as well as implying consistency with `get`. I'd therefore propose the method is renamed to `setAndReturn` and `setInAndReturn` in  order to help distinguish these things cognitively and provide a better match of language to what is actually happening.

**Comment by Methuselah96** [comment]
We're not going to change this. As you mentioned, this is fundamental to how immutable data works. There are too many methods that return the updated structure to suffix them all with `AndReturn`, there is no precedent in functional programming to use such verbose method names, and this is just something that you need to get used to if we working with Immutable.js.
