### ISSUE TITLE
Interested in Enum implementation?

### ISSUE THREAD

**Issue by philippefutureboy** [immutable-js/immutable-js#1426]
Hello!

I started building my own [library for data structures](https://github.com/we-human-space/JS-ADT/tree/dev/) (atm, only /src/components/node/ and /src/components/enum/ are up to date, rest dates from 2 years ago), but after seeing the wonderful library [mnemonist](https://github.com/Yomguithereal/mnemonist) by @Yomguithereal, I changed my mind :P 

I will be removing the said library shortly, and I wanted to know if the team at Immutable JS would be interested by a JS implementation of the Enum pattern as in Java and C#. I would gladly transfer my code over to the Immutable JS repository and make the necessary changes for proper integration with the library (whether vision-wise or implementation-wise). You can find the documentation for my Enum implementation [here](https://github.com/we-human-space/JS-ADT/wiki/Enumerable-Types-(Enum)), its implementation [here](https://github.com/we-human-space/JS-ADT/tree/dev/src/components/enum/enum.js), and its tests [there](https://github.com/we-human-space/JS-ADT/tree/dev/test/src/components/enum/enum.js).

Let me know what you think!

Cheers ✨

**Comment by philippefutureboy** [comment]
Bump: migrated the enum type to the repository https://github.com/we-human-space/enum-next

**Comment by Methuselah96** [comment]
See https://github.com/immutable-js-oss/immutable-js/issues/53#issuecomment-711036722.
