### ISSUE TITLE
Code typo in README.md

### ISSUE THREAD

**Issue by Ltrlg** [immutable-js/immutable-js#1431]
The following code snippet, copied from the readme, has one syntax errors and one logical error:
```js
const { Map } = require('immutable')
const map = Map({ a: 1, b: 2, c: 3 }
const lazySeq = Seq(map)
```

From what I understand, it should be written as follows:
```js
const { Map, Seq } = require('immutable')
const map = Map({ a: 1, b: 2, c: 3 })
const lazySeq = Seq(map)
```
(adding an imported identifier and a parenthesis)

**Comment by ajomadlabs** [comment]
Can I take up this ?
