### ISSUE TITLE
Splice fails to return an empty List when provided with the first and last elements. Instead keeps the last one.

### ISSUE THREAD

**Issue by mattgibson** [immutable-js/immutable-js#1447]
`expect(fromJS(['a', 'b', 'c', 'd']).splice(0, 3)).toEqual(fromJS([]));`

I think the above should work, but instead, I see this:

```
Expected value to equal:
  Immutable.List []
Received:
  Immutable.List ["d"]
```

This is with 4.0.0-rc.9

**Comment by zero298** [comment]
I think you are missunderstanding the [`splice()` API](http://facebook.github.io/immutable-js/docs/#/List/splice):
```
splice(index: number, removeNum: number, ...values: Array<T>): this
```

That says that you provide the index to start at, and the number of elements to remove.  I believe you think that you are supposed to provide the indices between which the elements should be inclusively deleted.  

Your test actually says that you are asking for **3 elements** to be removed from the list **starting at element 0**.  That means the elements `['a', 'b', 'c']` are removed leaving `['d']`.

I think your test should be: 
```
expect(fromJS(['a', 'b', 'c', 'd']).splice(0, 3)).toEqual(fromJS(['d']));
```

or:
```
expect(fromJS(['a', 'b', 'c', 'd']).splice(0, 4)).toEqual(fromJS([]));
```

**Comment by bj00rn** [comment]
close?
