### ISSUE TITLE
Record.get() with optional NSV (TypeScript)

### ISSUE THREAD

**Issue by dinony** [immutable-js/immutable-js#1463]
I'm using `v4.0.0-rc.9` with TypeScript.
I wonder why there is no [get](https://github.com/facebook/immutable-js/blob/v4.0.0-rc.9/type-definitions/Immutable.d.ts#L2391) method in the Record interface without the NSV value.
It results in a lot of `.get('..', null)` calls. Since I know that there is already a value, given that a record factory already enforces that a value is always present for all keys, it seems unnecessary.

**Comment by Zzortell** [comment]
I encounter the same issue.

**Comment by develra** [comment]
Woo! I could also use this.

**Comment by leidegre** [comment]
It's probably a typo, the `get` function is quite redundant if you have a record type. You would do `record.prop` or `record[prop]` over `record.get('prop', undefined)`. Maybe there are some optimizations I'm not aware of with respect to the Record type that makes this necessary but other than that, a Record is like a specialized Map so, the interface shouldn't really be different.

**Comment by lawrencezemour** [comment]
I'm glad that this was merged, ideally could you please release a new version with this fix? That would be awesome!

Also, it seems that the type for Record should allow direct access to properties, right?
