### ISSUE TITLE
Wrong typescript declarations for update method

### ISSUE THREAD

**Issue by JLarky** [immutable-js/immutable-js#1466]
### What happened

``` ts
update(key: K, updater: (value: V) => V): this;
```

here `updater` has wrong type, should be `updater: (value?: V) => V)` if key doesn't exist

### How to reproduce

``` ts
const good = I.Map<string, I.List<string>>().update("noKey", I.List(), a => a.map(x => x));
const bad = I.Map<string, I.List<string>>().update("noKey", a => a.map(x => x));
const fixed = I.Map<string, I.List<string>>().update("noKey", undefined as any, (a: undefined | I.List<string>) => a.map(x => x));
```
![image](https://user-images.githubusercontent.com/7026/34316402-941b0a18-e749-11e7-8fa4-ac3168970e01.png)

Here `good` works as expected, `fixed` shows error message that I would expect to see in this case `Object is possibly 'undefined'`, but `bad` doesn't show any errors while crashing at run time with `Uncaught TypeError: Cannot read property 'map' of undefined`

Maybe there need to be a function that is `updateIfKeyExist` that would have `(value: V) => V` type, but right now type is misleading and causes run time issues.

**Comment by JLarky** [comment]
I also noticed that you can return `undefined` from updater and it will delete the key from map, so I guess it's a `updater: (value: V | undefined) => V | undefined)`

**Comment by Zzortell** [comment]
@JLarky In Typescript `undefined` extends any type, so the updater type is `updater: (value?: V) => V)` which is fine.

**Comment by JLarky** [comment]
Not with --strict flag

**Comment by Zzortell** [comment]
Does Immutable support --strict flag ?

**Comment by JLarky** [comment]
Latest rc works with most of operations ok, and `update` is one of several
that still don't. For example `first()` was returning `V` and now it
returns `V | undefined` as expected, or `filter` was `(value?: V, key?: K)
=> boolean` but now it fixed and is `(value: V, key: K) => boolean`

**Comment by JLarky** [comment]
Noticed similar issue with `mapEntries` method. It allows you to return undefined instead of tuple to remove entry from collection so

```
   mapEntries<KM, VM>(
      mapper: (entry: [K, V], index: number, iter: this) => [KM, VM],
      context?: any
    ): Map<KM, VM>;
```

should be
```
   mapEntries<KM, VM>(
      mapper: (entry: [K, V], index: number, iter: this) => [KM, VM] | undefined,
      context?: any
    ): Map<KM, VM>;
```
