### ISSUE TITLE
Functional methods work incorrectly with native immutable data structures like Map\List

### ISSUE THREAD

**Issue by deser** [immutable-js/immutable-js#1472]
```js
Immutable.get((new Map()).set('a', '1'), 'a')
```
returns `undefined`

```js
Immutable.has((new Map()).set('a', '1'), 'a')
```
returns `false`
  
Btw, implementation of `get` embodies working with smth which has `get` function
![image](https://user-images.githubusercontent.com/3010698/34568184-10f79872-f176-11e7-8f90-5e40f981325b.png)

**Comment by deser** [comment]
![image](https://user-images.githubusercontent.com/3010698/34568125-dde3dbee-f175-11e7-92b8-17b609f39e17.png)

**Comment by rgbkrk** [comment]
The native `Map` object is _not_ immutable. If you want to work with it and `Immutable`, you need to create an `Immutable.Map` from a `Map`:

```
someMap = new Map([['a', 3]])
immutableSomeMap = Immutable.Map(someMap)
```

![screen shot 2018-01-11 at 10 45 38 pm](https://user-images.githubusercontent.com/836375/34862817-2ce62ed0-f721-11e7-8b88-6c4d1f3a6bd7.png)

**Comment by deser** [comment]
Why immutable.js makes assumption that collection could have function get which actually works as immutable get?

**Comment by rgbkrk** [comment]
Pass in bad data, get unexpected result. You need to pass in an Immutable Collection, not a native `Map`.
