### ISSUE TITLE
DeepMerge transforms Map to [key, value] Array in some conflicts

### ISSUE THREAD

**Issue by CharlieScarver** [immutable-js/immutable-js#1475]
Hello.
Using ```immutable@4.0.0-rc.9```
I was doing a ```.deepMerge``` and I ran into a conflict between a List and Map like this one: 
```javascript
const a = Immutable.fromJS({
    ch: [{
        code: 8
    }]
}); 
const b = Immutable.fromJS({
    ch: {
        code: 8
    }
});
const result = a.mergeDeep(b); 
/* result:
Map {
    'ch': List[
        Map { 'code': 8 },
        Array [ 'code', 8 ]
    ]
}
*/
```
Then I tried this:
```javascript
const a = Immutable.fromJS({
    ch: []
}); 
const b = Immutable.fromJS({
    ch: { code: 8 }
});
const result = a.mergeDeep(b); 
/* result:
Map {
    'ch': List[
        Array [ 'code', 8 ]
    ]
}
*/
```
I guess there's a problem when merging a key with a List value and a key with a Map value (the Map has 
 to have at least one key inside).
So I'm baffled by that Array there. 
Is this a bug?

Thank you.

**Comment by Cryru** [comment]
It's weird that an immutable merge returns a mutable array.

**Comment by hpurmann** [comment]
I can reproduce this with `4.0.0-rc.12`. @CharlieScarver what outcome would you expect in this case? I can't find any tests which does a mergeDeep with mixed List and Map for the same key. Isn't that just undefined behaviour?

**Comment by CharlieScarver** [comment]
Well, you're right. It is kinda undefined behavior.
The biggest issue is that it returns a normal JS Array. If that was just a Map { code: 8 } I wouldn't have raised this as an issue.
If it's Immutable, it would be fine whatever the behavior I guess- even an error, which may actually be pretty reasonable.
For me personally these options seem appropriate if an option is to be chosen:
```javascript
const a = Immutable.fromJS({
    ch: []
}); 
const b = Immutable.fromJS({
    ch: { code: 8 }
});
const result = a.mergeDeep(b); 

/* Optional results:
Map {
    'ch': List[
        Map { code: 8 }
    ]
}
===
Map {
    'ch': Map { code: 8 }
}
===
Map {
    'ch': Map { 
        code: 8,
        0: Map { code: 8 }
     }
}
*/
```
The first one would be best for me, but that's only for my specific case. 😕
