### ISSUE TITLE
Typing for updateIn is broken if last node is an OrderedMap

### ISSUE THREAD

**Issue by kvanbere** [immutable-js/immutable-js#1484]
### What happened

Maybe an occurrence of https://github.com/facebook/immutable-js/issues/1442 , maybe not.

### How to reproduce

This reproduces in our project with something like this:

```
/* @flow */

import { List, OrderedMap, Record } from 'immutable';

import type { RecordOf, RecordFactory } from 'immutable';

export type RootProps = {|
  oranges: OrderedMap<string, OrangeState>,
|};

export type RootState = RecordOf<RootProps>;

export const mkRootState: RecordFactory<RootProps> = Record({
  oranges: OrderedMap(),
});

export type OrangeProps = {|
  bumps: List<number>,
  square: boolean,
|};

export type OrangeState = RecordOf<OrangeProps>;

export const mkOrangeState: RecordFactory<OrangeProps> = Record({
  bumps: List(),
  square: true,
});

export const withOranges = (state: RootState, updater: (OrangeState) => OrangeState): RootState =>
  state.updateIn(['oranges'], updater);
```

We get a type error that `updateIn` does not belong to `state` when it is clearly a record of `RecordOf<RootProps>`, both with and without the `{| ... |}` exact object notation.

**Comment by donkeybonks** [comment]
Maybe fixed by #1464 .

**Comment by bryanrideshark** [comment]
@donkeybonks , did #1464 fix this or not?

Can we close this issue if it is indeed fixed?

**Comment by donkeybonks** [comment]
Not sure, I don’t work at that company anymore, sorry.

**Comment by acusti** [comment]
@leebyron I think if no one knows how to repro this or verify it, we should just close it.
