### ISSUE TITLE
`removeAll` and `deleteAll` are missing from `Map`

### ISSUE THREAD

**Issue by ghost** [immutable-js/immutable-js#1535]
### What happened
Was trying to use `deleteAll(['key1', 'key2', 'key3'])` on a `Map` object but it noted that the method is undefined. On inspection it doesn't seem this method is on defined.

### Version
Currently, the project is using Immutable 4.0.0-rc.9.

### How to reproduce
Inspect the `Map` object and look for `deleteAll` or `removeAll`. Alternatively, try to create a Map and use the method on it.

![screen shot 2018-05-21 at 5 14 38 pm](https://user-images.githubusercontent.com/310165/40336024-d76289f2-5d1b-11e8-9676-4e56344f09af.png)

**Comment by bohdanbirdie** [comment]
@aktof just checked current (4.0.0-rc.9.) version in the browser, seems to work

![image](https://user-images.githubusercontent.com/23266928/43424071-da6c580e-9456-11e8-9248-fd7f5bad910a.png)

**Comment by aktof** [comment]
@bohdanbirdie Thanks for getting back, will check and confirm.
