### ISSUE TITLE
Immutable nested object are still referenced.

### ISSUE THREAD

**Issue by EsmeraldiBejolli** [immutable-js/immutable-js#1551]
---  Have a question  ---

### What happened
I have created new Map using immutable js

```javascript
const myMap = Map({
    myobject: { 
        nesetedObject: {
            DeepNestedObject : 'My deep nested object values '
        }
    }
}); 


but I can still mutate nested objects.

```javascript 
const myCustomMap = myMap.get('myObject')
myCustomMap.nesetedObject.DeepNestedObject  = ' ';
console.log(myMap.get(myObject)) //         nesetedObject: {DeepNestedObject : ' '}


Is there any way to make those nested objects more immutable without creating other Map() and nest Map().

**Comment by Brantron** [comment]
Will `fromJS` get you what you need?

https://jsfiddle.net/1u2ew67x/

**Comment by bhowell2** [comment]
As far as I know there is not another way (with this library) to make the objects immutable, without actually using an immutable data structure. You could lock the objects with `Object.freeze`.. but you're just adding more complexity. As Brantron said, you could use `fromJS` which will convert inner objects to Maps and Lists automatically. HOWEVER, you can't just apply it on your top-level Map with nested POJOs or it's not going to convert them, the input into `fromJS` needs to be a POJO itself.

**Comment by conartist6** [comment]
You might consider using a package like [deep-freeze-strict](https://www.npmjs.com/package/deep-freeze-strict).

Then you'd have:
```js
const deepFreeze = require('deep-freeze-strict');
const myObject = {
    myobject: { 
        nesetedObject: {
            DeepNestedObject : 'My deep nested object values '
        }
    }
};
//  either
const myMap = Map(deepFreeze(myObject));
// or
Immutable.fromJS(myObject);
```

The down side of using `deepFreeze` is that it's not creating a frozen version, it's freezing the original.

The down side of fromJS is that you lose the ability to reference the inner objects using `.`, you'll have to navigate them with `.get`
