### ISSUE TITLE
Make Old Doc Versions Available

### ISSUE THREAD

**Issue by brombomb** [immutable-js/immutable-js#1639]
I am using an older version of immutable at work, 3.8.0.  while reading the 4.0 docs I found a useful function and went to implement it only to be denied.  It'd be nice to have a reference to the docs I am using in production available so that I don't have to worry about checking for backwards compatibility.

**Comment by conartist6** [comment]
Managed to get gulp to check out `Immutable.d.ts` from each of those versions into their own files and run the doc generator on them creating many versioned copies of `immutable.d.json`. Versions prior to 3.0 fail with error: `Unknown type kind: VoidKeyword`. Seems like a pretty big win to get the whole 3x series, so I'll ignore this for now.

**Comment by conartist6** [comment]
Next I'll need to update the static html job. Currently it just produces index.html, for the main page and docs page, it will need to produce one html file for each page for each documented version.

**Comment by conartist6** [comment]
Got gulp to output multiple docs HTML files, each rendering the (sort of) correct summaries. It seems the formatting expected in the Sequins.d.json file has changed a bit over time. Not sure how to handle this in the long run. We could release patch versions on the 3x line to bring them up to speed with the modern doc generator, but that would break the way they work with the doc generator that they ship with. Alternatively we could attempt to make the modern doc generator either aware of past formats. This seems safest.

Navigation is within the versioned doc files is broken at the moment, this will require some changes to router and link generation code.

**Comment by conartist6** [comment]
After I fix that I'll have to consolidate the headers for the two pages (why has this not been done already) and make the version - currently displayed as Docs(version) - into a dropdown of hyperlinks. Also I'll need to adjust how it knows what the current version is. Currently the frontend grabs it straight out of package.json, it'll need to be fed into immutable.d.json first and used from there.

**Comment by conartist6** [comment]
OK, had to generate JSONp versions of the defs and load them up via script tag as opposed to just bundling them in. I now have a build which outputs several html files named for versions each of which is a usable doc site showing the correct doc data for that version. I just need to make the navigation links, figure out how to handle the README page, and perhaps change the github links to reflect version as well.

**Comment by conartist6** [comment]
@brombomb If it will help you and your coworkers (or anyone else!) now while I finish up the functionality for everyone, here is the documentation site for 3.8:

http://burningpotato.com/immutable-docs/docs/3.8.html

**Comment by brombomb** [comment]
nice work @conartist6 :)
