### ISSUE TITLE
Not reset value 

### ISSUE THREAD

**Issue by navata** [immutable-js/immutable-js#1670]
import * as Utils from "./utils";
let menus = Utils.menus;

I use immutable update variable menus. But Utils.menus not reset value.
It's same as cache memory. Please look at the picture below (length = 2 but it have 13 elements).

![screen shot 2019-01-07 at 17 23 32](https://user-images.githubusercontent.com/16706514/50763049-4fd67480-12a1-11e9-8942-b075b7e88ee0.png)

**Comment by conartist6** [comment]
Please include more information. I can tell you for sure that from what you've posted here, nobody will be able to help you at all. Could you post a complete reproduction online somewhere?

**Comment by marianoguerra** [comment]
can someone with permissions close this issue as inactive and no further info provided?
