### ISSUE TITLE
isEmpty methods removed?

### ISSUE THREAD

**Issue by marek-nogiec** [immutable-js/immutable-js#1681]
`Record#isEmpty` method seems to be removed. Was it moved or replaced? Can't seem to find any info about it in the changelog or docs

**Comment by ThomasdenH** [comment]
In #1135, `Record` stopped extending `Collection`. I think that's it. The size of a record doesn't change, but I think you can use `record.toSeq().isEmpty()` if you want to know the size.

**Comment by marek-nogiec** [comment]
That must be it, thanks a lot!

**Comment by marianoguerra** [comment]
@marek-nogiec can you close this issue? thanks!
