### ISSUE TITLE
how to get next element in immutable List when use map

### ISSUE THREAD

**Issue by bonusbb** [immutable-js/immutable-js#1687]
if   const a = new List([new Map({ title: 'first', startTime: '09:00:00', endTime: '12:00:00', complete: true }),
		               new Map({ title: 'second', startTime: '14:00:00', endTime: '16:00:00', complete: false }),
			          ]),

when i use a.map((value,index) => {
//HOW TO GET VALUE OF NEXT ELEMENT IN HERE ?
})

**Comment by Monar** [comment]
http://facebook.github.io/immutable-js/docs/#/List/map
