### ISSUE TITLE
http://immutable-js.com/ directs to a 404

### ISSUE THREAD

**Issue by thepont** [immutable-js/immutable-js#1694]
### What happened

Seems that the immutable-js.com domain is pointing to the wrong location on github, going to the site now directs to a 404.

I realise that this isn't an issue with the lib, but it's unclear how to notify anyone of this issue.

### How to reproduce

go to http://immutable-js.com

**Comment by sravan-s** [comment]
I thought https://immutable-js.github.io/immutable-js/ is the official website

**Comment by thepont** [comment]
I don't know, It's the link on the organization page.

![2019-02-20-092446_1395x1087_scrot](https://user-images.githubusercontent.com/2901992/53051879-65ba9480-34f1-11e9-8978-9480d98935ae.png)

**Comment by thepont** [comment]
It's the URL on the organisation page.  I think it just used to redirect the facebook immutable-js GitHub page that no longer exists?

![2019-02-20-092446_1395x1087_scrot](https://user-images.githubusercontent.com/2901992/53051949-8da9f800-34f1-11e9-8c08-2d1f2c56edb5.png)

**Comment by Methuselah96** [comment]
Resolved.
