### ISSUE TITLE
is the latest release stable v4.0.0-rc.12 ?

### ISSUE THREAD

**Issue by pavelthq** [immutable-js/immutable-js#1698]
Hello, just noticed that in releases section latest version v4.0.0-rc.12 is not a pre-release, can you confirm that it is stable to use in production?

Thanks, Pavel

**Comment by conartist6** [comment]
I would not consider it so.

**Comment by ablakey** [comment]
ImmutableJS feels pretty stable so I'm not expecting a lot of traffic. But we've been on RC12 for a long time and it looks like not much is happening anymore. Is a release going to occur soon?

**Comment by jaulz** [comment]
@ablakey great to hear! Are you planning to release it on npm under 4.0 sometime soon?

**Comment by conartist6** [comment]
If you look at the list of issues I think you’ll find quite a few things in there that need to be fixed before the library is stable under 4.0. That many reported issues haven’t been acknowledged much less fixed does not diminish their existence.

As it stands we’re all dead in the water without anybody active on the project who has commit privs, so the answer to this question is ¯\_(ツ)_/¯

**Comment by JustFly1984** [comment]
Does anybody wants to join me in refactoring this library to typescript in new repo, and call it ‘immutable-ts’ ?

**Comment by mzedeler** [comment]
@conartist6 + @ablakey: I can contribute by listing the blocking issues that needs to be fixed before 4.0 can be released. I have been using immutable.js intensively for two years now, so I should be able to identify the most obvious ones.

**Comment by mzedeler** [comment]
I found this one:

https://github.com/immutable-js/immutable-js/milestone/1

**Comment by mzedeler** [comment]
Oh, well. I found this too: https://github.com/immutable-js/immutable-js/issues/1494

**Comment by JLarky** [comment]
> Hello, just noticed that in releases section latest version v4.0.0-rc.12 is not a pre-release, can you confirm that it is stable to use in production?

Given https://github.com/immutable-js/immutable-js/issues/1494#issuecomment-416218375 it's hard to recomend using any version of immutable-js really.

But https://github.com/immerjs/immer is stable to use in production if that's any help.

**Comment by Jessidhia** [comment]
It might be good to not publish it under the `latest` tag in npm then. `-rc.12` was published as `latest` instead of `rc`, while `rc` still points to `-rc.11`: https://www.npmjs.com/package/immutable
![image](https://user-images.githubusercontent.com/73085/61862238-8788cf00-af08-11e9-835c-cfc2dddf123c.png)
