### ISSUE TITLE
Updating the state with nested Immutable records

### ISSUE THREAD

**Issue by KakarN** [immutable-js/immutable-js#1708]
I have an Immutable record for an Editor, which has nested records for the content and selection.

So whenever the selection changes, I would get the start and end points of the selection, and then update the state with a new selection.

```
class SelectionStateRecord extends Immutable.Record({
        anchor: 0,
        focus: 0,
    }
) {
    // extra features
}

class EditorRecord extends Immutable.Record({
        key: uuid.v4(),
        ContentState: new ContentStateRecord(),
        SelectionState: new SelectionStateRecord(),
    }
) {
    // extra features
}

export default class TextEditor extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            EditorState: new EditorRecord()
            ...
        }
    }

    _onSelectionChange = e => {
        const {start, end} = e.nativeEvent.selection
        const newEditorState = this.state.EditorState.SelectionState.merge({
            focus: start,
            anchor: end,
        })
        this.setState({EditorState: newEditorState})
    }

    render() {
        ...
    }
}
```

But, I am getting this error, I am guessing I cannot just set a new value to a nested record:

> undefined is not an object (evaluating '_this.state.EditorState.SelectionState.merge')

However, this works as expected:

```
    _onSelectionChange = e => {
        const {start, end} = e.nativeEvent.selection
        const newEditorState = this.state.EditorState.merge({
            key: uuid.v4(),
            ContentState: this.state.EditorState.ContentState,
            SelectionState: this.state.EditorState.SelectionState.merge({
                focus: start,
                anchor: end,
            }),
        })
        this.setState({EditorState: newEditorState}, () => {
            console.log('start', this.state.EditorState.SelectionState.start())
        })
    }
```

I am just not sure if this is the right way to update the state, and confused how to set/update values to a individual nested Immutable record as to avoid performance loss.

**Comment by JustFly1984** [comment]
I do not recall exact source, but I have been told that Records is not suitable for React state management, cos it does not have persistence features, which Map and List has. I had this conversation about 2 years ago. If there is some changes since 3.82, please correct me if I’m wrong.

**Comment by marianoguerra** [comment]
`const newEditorState = this.state.EditorState.SelectionState.merge`
returns a new SelectionStateRecord instance, not a new EditorState instance, you are then updating the state in `this.setState({EditorState: newEditorState})` with an instance of SelectionStateRecord and not with an instance of EditorState, it seems at some point when it tries to access SelectionState on the new instane of SelectionStateRecord (which doesn't have it) it throws undefined is not an object.

@KakarN can you (or someone with permissions) close this issue?
