### ISSUE TITLE
List.insert makes the inserted object into an array in IE 11

### ISSUE THREAD

**Issue by dbwcooper** [immutable-js/immutable-js#1711]
### What happened

List.insert makes the inserted object into an array in IE 11 

IE version : 11.648.17134.0

I use IE 11 to open https://immutable-js.github.io/immutable-js/docs/#/List to test in the console.

### How to reproduce
1. Defined an object list
2. Insert an object at the beginning of the list 
3. The first object becomes an array

e.g.
```
var a= Immutable.fromJS({ a: 0 })
var b = Immutable.fromJS({ b: 0 })
var c = Immutable.fromJS({ c: 0 });
var list = Immutable.fromJS([b, c])

var newlist = list.insert(0, a); 
// expect [Object, Object, Object]
// actual:  [Array, Object, Object]
```
pic 
![image](https://user-images.githubusercontent.com/22339946/58090578-14a66380-7bfa-11e9-8499-7afef780c64b.png)

**Comment by jdeniau** [comment]
I reduced the issue to the following :

```js
List().concat(['foo']));
// output : 
// non-ie : ["coucou"] 
// ie : [["coucou"]]
```

If we concat like this, it does work

```js
List().concat(List(['foo'])));
```

In this issue, it is called here : https://github.com/immutable-js/immutable-js/blob/c02d7694f8c72a5589bbad509ffd7fb404486ed2/src/CollectionImpl.js#L590
