### ISSUE TITLE
Deep Merge with same key of different value type (Map vs List) does not merge as expected

### ISSUE THREAD

**Issue by trevorlitsey** [immutable-js/immutable-js#1719]
### What happened

When deep merging two Maps with the same key name but different value types, no merge is done and the key's value remains unchanged. I would expect the value to be overwritten.

### How to reproduce

```
var objWithObj = Immutable.fromJS({ 
  items: { 
    '1': { 
      id: '1'
    } 
  } 
})
var objWithArray = Immutable.fromJS({ 
  items: [{
    id: '1'
  }] 
})
var mergedObj = ObjWithObj.mergeDeep(objWithArray)
```

**Comment by jay-deshmukh** [comment]
Facing the same issue.  @trevorlitsey how did you manage to solve this ?
