### ISSUE TITLE
Search bar in docs does not work

### ISSUE THREAD

**Issue by aacunningham** [immutable-js/immutable-js#1720]
### What happened

When browsing the docs at https://immutable-js.github.io/immutable-js/docs/ I tried to use the search bar to get to the Record page. After typing in "record" and clicking on the first result, I was redirected to the home page.

When I click on a result from the search bar, I should be taken to the page related to that result

I did a little digging and it looks like the search results from algolia are pointed at the domain facebook.github.io, which redirects to immutable-js.github.io without passing the URL ID fragment.

### How to reproduce

1. Go to https://immutable-js.github.io/immutable-js/docs/
2. Type "record" into the search bar at the top
3. Select any result
4. You should be redirected to https://immutable-js.github.io/immutable-js/

**Comment by leebyron** [comment]
I reached out to Algolia and this is now resolved!
