### ISSUE TITLE
Map and Set are not converted to Immutable.Map and Immutable.Set via Immutable.fromJS()

### ISSUE THREAD

**Issue by marinovich** [immutable-js/immutable-js#1723]
### What happened

There is no way to create Immutable.Map and Immutable.Set from Map and Set via Immutable.fromJS()

### How to reproduce

```js
const set = new Set([1, 2, 3]);
const immutableSet = Immutable.fromJS(set);

console.log(set === immutableSet) // true
``` 

And the same with Map

**Comment by conartist6** [comment]
Yep. I actually hope to solve this with an independent library which would be responsible for detecting structures which implement the Map/Set protocols, either by being or extending native Maps or Sets, being Immutable maps or sets, or by using symbols it exports as markers of custom Maps or Sets.
