### ISSUE TITLE
Issue with Map keys type

### ISSUE THREAD

**Issue by marlo22** [immutable-js/immutable-js#1725]
Hi there :smile: 

I'm writing tests to my app and I have interesting problem with Immutable structures. In my components I use Redux selector with params "district” (string) and "compositionId" (number). This selector looks like this:
```js
getCompositionTopicalSearchTools: (state, district, compositionId) =>
    state.searchTools.getIn([
      'compositionSearchTools',
      district,
      compositionId
]) || List([]),
```

Setting this object in reducer looks like this:
```js
const fetchCompositionTopicalSearchToolsSuccess = (state, action) => {
  const { district, compositionId, tools } = action;
  return state.setIn(
    ['compositionSearchTools', district, compositionId],
    List(tools)
  );
};
```

When I run app, this selector works well and return data from state, but when I run it on test environment I have to coerce `compositionId` parameter to string and only then test is passed.
```js
  it('getCompositionTopicalSearchTools', () => {
    const district = 'warsaw';
    const compositionId = 73;
    const tools = List([{ id: 1, name: 'Districts' }, { id: 2, name: 'Area' }]);

    const state = {
      searchTools: Map({
        compositionSearchTools: Map({
          [district]: Map({
            [compositionId]: tools
          })
        })
      })
    };

    expect(
      getCompositionTopicalSearchTools(state, district, String(compositionId))
    ).toEqual(tools);
  });
```

I don't understand why in app this selector works well without coercing `compositionId` parameter to string. I read that in Immutable Map keys always are string, even if they are passed as numbers. Why in app environment key passed as number works well but, in tests environment not? What is the difference between these cases? This is bug?

**Comment by marlo22** [comment]
Solved - problem was in test suite. When I defined `const state` by `setIn` (as in reducer) instead of declare JS object everything works well. But still, I don't know why previous approach didn't work.

**Comment by acusti** [comment]
@marlo22 Glad you were able to solve that, and thanks for the repro and for updating the issue! The unexpected behavior is a consequence specifically of how native JS object literals work. When you were doing:
```js
{
  [compositionId]: tools
}
```
regardless of what type of value `compositionId` is, it gets coerced to a `string`. You can see that in action by running `Object.keys()` on the result, e.g.: `Object.keys({ 40: 'forty' })`

Also, if your issue has been fully solved, could you close it? Thanks again!

**Comment by marlo22** [comment]
@acusti thanks for answer! :+1: I close this issue. :smiley:
