### ISSUE TITLE
Why is the wrong Immutable.js Map factory function selected when running npm test?

### ISSUE THREAD

**Issue by donders** [immutable-js/immutable-js#1729]
As described in this SA post in more detail: https://stackoverflow.com/questions/57557106/why-is-the-wrong-immutable-js-map-factory-function-selected-when-running-npm-tes?noredirect=1#comment101576259_57557106

Trying to use the 'collection'  notation of the factory functions for Map causes a transpiler error. It seems Typescript is unable to determine the intent of the two dimensional collection. Is the documentation still up to date?

**Comment by jdeniau** [comment]
Hi, 

Thanks for your report. This should be fixed in `4.0.0-rc.14`. 

Please re-open this issue if this is not the case.
