### ISSUE TITLE
sortBy documentation is wrong

### ISSUE THREAD

**Issue by Desentso** [immutable-js/immutable-js#1739]
### What happened

The [documentation](https://immutable-js.github.io/immutable-js/docs/#/List/sortBy) states that you can use sortBy like this `hitters.sortBy(hitter => hitter.avgHits)`.

So this `Immutable.fromJS([{a: 1}, {a: 5}, {a: 2}]).sortBy(elem => elem.a).toJS()` should print something like: 
```
[
  {a: 1},
  {a: 2},
  {a: 5}
]
```
but it actually does nothing to the list and just prints it in the initial order:
```
[
  {a: 1},
  {a: 5},
  {a: 2}
]
```

When you use sortBy like this `Immutable.fromJS([{a: 1}, {a: 5}, {a: 2}]).sortBy(elem => elem.get("a")).toJS()` it works. 

**So the documentation should be updated to `hitters.sortBy(hitter => hitter.get("avgHits"))`**

### How to reproduce

Just test yourself e.g. on the docs page and see what 
`Immutable.fromJS([{a: 1}, {a: 5}, {a: 2}]).sortBy(elem => elem.a).toJS()` prints
and what `Immutable.fromJS([{a: 1}, {a: 5}, {a: 2}]).sortBy(elem => elem.get("a")).toJS()` prints

**Comment by conartist6** [comment]
There's no bug in the docs. You were just surprised that `fromJS` converted your objects into maps -- which isn't something you got from the docs. All you need to change to make your code work is change `fromJs` to `List`. It might look like:
```js
Immutable.List([{a: 1}, {a: 5}, {a: 2}]).sortBy(elem => elem.a).toJS()
```
