### ISSUE TITLE
merge Map with Array<{[key: string]: C}>

### ISSUE THREAD

**Issue by GolubevS** [immutable-js/immutable-js#1746]
### What happened

Map is not merging with array of objects

### How to reproduce

```
import { Map } from 'immutable';

const myMap = Map({ a: 10, b: 20, c: 30 });
const mergedMap = myMap.merge([{b: 40}, {a: 50}, {d: 60}]);

console.log(mergedMap.toJS());
```
Expected:

{ "a": 50, "b": 40, "c": 30, "d": 60 }

Result: 

{ "a": 10, "b": 20, "c": 30, undefined: undefined}

**Comment by Methuselah96** [comment]
The `merge` method takes rest parameters of collections not an array of collections which is why you're having issues. (I agree that the documentation is easy to misread.)
