### ISSUE TITLE
Is project still active?

### ISSUE THREAD

**Issue by chunfantasy** [immutable-js/immutable-js#1747]
Just wondering whether the project is active or not?

**Comment by opr** [comment]
Hi, no "official" statement, but see here for more discussion https://github.com/immutable-js/immutable-js/issues/1689

**Comment by Emobe** [comment]
Blame facebook. These big companies like to pander to developers but cannot cope with open source. So many people would work on this plugin.

**Comment by chrisVillanueva** [comment]
Thanks @opr.  Our team pulled immutablejs for a dependency in a large project.  Need insight on roadmap/future plans.

**Comment by Methuselah96** [comment]
As of now, yes, we're working on getting a stable 4.x release. See https://github.com/immutable-js/immutable-js/issues/1689#issuecomment-863599993 for the latest.
