### ISSUE TITLE
Map.toArray() does not match document description

### ISSUE THREAD

**Issue by hanayashiki** [immutable-js/immutable-js#1755]
As title

### How to reproduce

```
let m = Map();
m.set(1, 1);
console.log(m.toArray()) // Prints [[1, 1]], should print [1]
```
According to your doc, it should return just values.
https://devdocs.io/immutable/index#map.toarray

**Comment by bdurrer** [comment]
@hanayashiki The referenced website describes version 3.8.1, it is not up to date.

The [official documentation](https://immutable-js.github.io/immutable-js/docs/#/Map/toArray ) says

> toArray(): Array<[K, V]>
> Shallowly converts this collection to an Array.
