### ISSUE TITLE
Type Checking is broken for primitives

### ISSUE THREAD

**Issue by rohitpratapitm** [immutable-js/immutable-js#1760]
### Set<**string**> is allowing users to pass Set<**number**>.
// passing NUMBERS in a set of STRING
`  set: Set<string> = Set<string>([1,2,3]);`
**Type checking should be enforced while using generics.**
### How to reproduce
See stackblitz here : 
[angular-immutable-js-generics-issue](https://stackblitz.com/edit/angular-immutable-js-generics-issue)
<!-- Provide enough information that someone else could produce the same error.

**Comment by Methuselah96** [comment]
This is fixed in `immutable@4.0.0-rc.12`:

```
import { Set } from 'immutable';

const set: Set<string> = Set<string>([1,2,3]);

```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZQKbwL5wGZQiOAclBAFcYBDAIwBtVCBuAKCYGMIA7AZ3i-QC4U6ADw8owDgHMAfHAC8QmKJjip0gBQBtAIwAaAEy6AzAF0AlMyA)
