### ISSUE TITLE
Typescript definitions: RecordOf has no size property

### ISSUE THREAD

**Issue by tareqdayya** [immutable-js/immutable-js#1763]
The typescript definition files for RecordOf do not list a size property even though the docs demonstrate it being used. As a result, the TS compiler keeps complaining every time i use size on a record.

**Comment by Methuselah96** [comment]
Actually, records do not have a `size` property, the docs were incorrect. I've made a PR to fix the docs: https://github.com/immutable-js/immutable-js/pull/1779.

**Comment by jdeniau** [comment]
Thank you for your bug report. The immutable-js oss fork will soon be merged and a fix for this issue has been included in #1833. Once this PR is merged, this issue will be resolved in the main branch. We will then do our best to to release the `4.0.0` version.
