### ISSUE TITLE
Docs sidebar links broken (Firefox)

### ISSUE THREAD

**Issue by alexkrolick** [immutable-js/immutable-js#1765]
List => https://immutable-js.github.io/List 404s

EDIT: all links from the homepage to specific APIs are not working

If someone else needs to find the docs for the latest stable version, try the typedefs https://github.com/immutable-js/immutable-js/blob/v3.8.2/type-definitions/Immutable.d.ts

![Kapture 2020-03-24 at 15 38 18](https://user-images.githubusercontent.com/1571667/77483528-98fedf80-6de5-11ea-8d6e-a3f7549ee97d.gif)

---

Occurring on Firefox; the page redirects immediately on Safari

**Comment by zhaozhemin** [comment]
Did you happen to use an ad blocker? If so, try allowing third party scripts.

**Comment by alexkrolick** [comment]
Hmm, either FF or my VPN doesn't trust the cert for https://cdn.jsdelivr.net/react/0.12.1/react-with-addons.min.js

```
An error occurred:: SEC_ERROR_UNKNOWN_ISSUER
```
