### ISSUE TITLE
Insert value as object on null

### ISSUE THREAD

**Issue by piyaleemaiti** [immutable-js/immutable-js#1771]
### What happened

```
const original = { x: { y: null}}
setIn(original, ['x', 'y', 'z'], 456)
```

Here the old value was set to null, but I wanted to insert object value replace of null, how can I do that?

**Comment by bdurrer** [comment]
Please use stackoverflow for questions. The issues on github are meant for bug/improvment reports.

PS: You likely forgot to assing the returned new collection: 
`notOriginalAnymore = setIn(original, ['x', 'y', 'z'], 456)`

**Comment by Methuselah96** [comment]
@piyaleemaiti I think the only way to do what you're asking is to provide the object value you want to replace `null` with like this:

```
const original = { x: { y: null}}
const result = setIn(original, ['x', 'y'], { z: 456 })
```

**Comment by piyaleemaiti** [comment]
Thanks @Methuselah96, I will try your suggestion.
