### ISSUE TITLE
release v4? it's been an rc for 2 years and the -rc on the npm version breaks semantic versioning checks in some cases

### ISSUE THREAD

**Issue by scamden** [immutable-js/immutable-js#1781]

**Comment by lxcid** [comment]
Feel better @leebyron @scamden. Thanks for the update!

**Comment by jdeniau** [comment]
Hi!
The 4.0.0-rc.14 version has been released and should fix this issue.
Feel free to test it and re-open this issue if the issue is still present.
We will try to make stable 4.0 version a reality, but we still have some issues to close until then. 
Thank you!
