### ISSUE TITLE
Empty record merge returns undefined

### ISSUE THREAD

**Issue by acrazing** [immutable-js/immutable-js#1785]
For example:

```ts
import { Record } from 'immutable';

const emptyRecord = Record({})();

console.log(emptyRecord.merge({ id: 1 })); // -> undefined, expected result is emptyRecord
```

See [CodeSandbox](https://codesandbox.io/s/headless-sun-75vvc?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ma-6cji** [comment]
Empty record merge returns undefined immutable-js-oss/immutable-js#28 
 plplease  check or delete   thank  you

**Comment by acrazing** [comment]
Thank you.
