### ISSUE TITLE
Can't assign string to string | null for object in immutable map

### ISSUE THREAD

**Issue by NinthDesertDude** [immutable-js/immutable-js#1788]
### What happened
With typescript 3.9.7 and immutable-js version 3.8.2, the following code unexpectedly throws an error:

```
type TestAbcType = IImmutableMap<{ a: boolean, b: string | null }>
const testAbc = createImmutableMap({ a: true, b: null })
const testXyz: TestAbcType = testAbc
```

With the error being:

```
Type 'IImmutableMap<{ a: boolean; b: null; }>' is not assignable to type 'TestAbcType'.
  Type 'string | null' is not assignable to type 'null'.
    Type 'string' is not assignable to type 'null'.
```

This is surprising because according to the type definition, `b` can be a string or null. In this case, b is null and should satisfy the condition of `string | null`. This code works if it's not wrapped with IImmutableMap, indicating the problem lies with this library.

**Comment by conartist6** [comment]
You hav not included the definition of `IImmutableMap`.
