### ISSUE TITLE
Immutable objects are still mutable

### ISSUE THREAD

**Issue by mesolido** [immutable-js/immutable-js#1793]
I just came across your library.

I tried this on the example you provided on https://immutable-js.github.io/immutable-js/
`map1._root.entries[1][1] = 50`
Then, if I print `map1.get('b')`, its value is effectively 50

How is that possible, since `map1` is supposed to be immutable.

Also, it is possible to add new entries to `map1`.
`map1._root.entries.push(['d', 4])`
`map1.size = 4`
`map1.get('d')` gives 4

Am I misunderstanding or your data structures are not really immutable ?

**Comment by Methuselah96** [comment]
@mesolido `_root` is a private variable that should only be used the library internally. You shouldn't be accessing or modifying variables that start with `_`.
