### ISSUE TITLE
FYI - immutable-js ported to Deno

### ISSUE THREAD

**Issue by oguimbal** [immutable-js/immutable-js#1798]
I ported immutable-js so it is usable in Deno.

You can find it at [https://deno.land/x/immutable](https://deno.land/x/immutable) Let me know if you have any problem with that :)

(And thank you for this great lib !)

**Comment by jdeniau** [comment]
Hi,

Thanks for this. I do not know if this is really useful in comparaison to npmjs.
If it is, can we make the process automatic ? I don't think you want to update your fork, build, and publish every time we publish a new version here. (the `4.0.0-rc.14` is not published for example).

**Comment by oguimbal** [comment]
Hi,

You cannot use npm packages in Deno. (its module system is VERY different from that of Node).
So it is not really a matter of comparison: You dont have a choice when using Deno.

I'll think about automating it, but I dont have time these days - I'm adding that to my todolist.

In the meantime, I updated & published 4.0.0-rc.14 on deno.land (see [this commit](https://github.com/oguimbal/immutable-js-deno/commit/c8f39292ba60367ac3b6a73e511cbc4cc4253f54))

**Comment by jdeniau** [comment]
OK great ! 👍 

I'm closing this as user that want to search immutable on deno will find https://deno.land/x/immutable@4.0.0-rc.14-deno ! 🎉

**Comment by vegerot** [comment]
I've noticed that https://deno.land/x/immutable has not been updated in a while.

Are there any plans on moving [immutable-js-deno](https://github.com/oguimbal/immutable-js-deno) to `immutable-js/immutable-js-deno` or something?  As well as providing automatic releases?

Also, on the note of
> You cannot use npm packages in Deno. (its module system is VERY different from that of Node).

Moving immutable js to 100% esm support (by changing `type` in package.json to `type: module`) will then make `immutable` essentially back-and-forth compatible with Deno

**Comment by jdeniau** [comment]
Can anybody sum up what needs to be done to make immutable compatible with deno ?

**Comment by oguimbal** [comment]
Hi, I publisher of [https://deno.land/x/immutable](https://deno.land/x/immutable) here... 
I could transfer ownership to owners of immutable-js if needed, just ping me 🙂

This Denoified version of immutable is just a hack (literraly [3 lines of code](https://github.com/oguimbal/immutable-js-deno/blob/master/mod.ts)) that exports the js bundle of immutable-js, and its type definition.

That does the trick (or at least used to) for the Deno interpreter, so you could use as if it was an actual Typescript bundle.

I think that upgrading to a newer immutable-js should be very straightforward using the same trick.

I dont have much time to do that and test it with a newer version of Deno at the moment, but if someone is willing to do it, I'd gladly accept a pullrequest.

**Comment by jdeniau** [comment]
If this is only a matter of this single file, can we include it in the main immutable package ? 
(If I remember correctly, thoses files did change and should be simpler now, no "ambiant" stuff) since https://github.com/immutable-js/immutable-js/pull/1854

**Comment by oguimbal** [comment]
Yes, but would have to commit the built js bundle as well, in order to make it downloadable by Deno (that's why I excluded [those](https://github.com/oguimbal/immutable-js-deno/tree/master/node_modules/immutable/dist) from `.gitignore`)
