### ISSUE TITLE
Read the Docs link at https://immutable-js.github.io/immutable-js/ is broken

### ISSUE THREAD

**Issue by Qoll** [immutable-js/immutable-js#1800]
Clicking on the Read the Docs link under the section Documentation at [https://immutable-js.github.io/immutable-js/docs/#/]( https://immutable-js.github.io/immutable-js/) leads to "Page not found error"

The Docs link in the website header works and goes to [https://immutable-js.github.io/immutable-js/docs/#/](https://immutable-js.github.io/immutable-js/docs/#/) while Read the Docs link goes to [https://immutable-js.github.io/immutable-js/docs/#/](https://immutable-js.github.io/immutable-js/docs/)

**Comment by Methuselah96** [comment]
Resolved by https://github.com/immutable-js/immutable-js/pull/1823.
