### ISSUE TITLE
TypeScript 4.1.2 resolves notSetValue to unknown

### ISSUE THREAD

**Issue by pedro-pedrosa** [immutable-js/immutable-js#1806]
### What happened

The TypeScript signature of methods like `first`, `last`, etc that take a `notSetValue` is:

```ts
first<NSV>(notSetValue?: NSV): V | NSV;
```

In TypeScript (at least in `4.1.2`) if no argument is passed, `NSV` becomes `unknown`, not `undefined` as documented.

Possible fix:

```ts
first<NSV = undefined>(notSetValue?: NSV): V | NSV;
```

I found this PR but it never got merged: #1653. I think `= undefined` is less verbose as it doesn't create a new overload. If going with this overload approach, the correct declaration would be (instead of the one in the PR):

```ts
first(): V | undefined;
first<NSV>(notSetValue?: NSV): V | NSV;
```

I'd create a PR but didn't know how you wanted to handle #1653.

Note that other methods that accept a `notSetValue` argument probably suffer from the same issue.

Thank you.

**Comment by Methuselah96** [comment]
This has been resolved in https://github.com/immutable-js/immutable-js/pull/1676, but hasn't been released yet.
