### ISSUE TITLE
Compare two objects if they are identical or not  using immutable-js?

### ISSUE THREAD

**Issue by sahilrajput03** [immutable-js/immutable-js#1809]
Is it possible to compare two objects using immutablejs's api , i mean just like lodash has this [function](https://lodash.com/docs/4.17.15#isEqual)??

**Comment by acusti** [comment]
it is! [`Immutable.is(foo, bar)`](https://immutable-js.github.io/immutable-js/docs/#/is) will do the same as `_.isEqual(foo, bar)` but for immutable collections. every collection also has [`.equals()`](https://immutable-js.github.io/immutable-js/docs/#/Map/equals), which uses `Immutable.is`, so `foo.equals(bar)` will also do the same thing.

**Comment by sahilrajput03** [comment]
Thanks acusti for helping me out.!! :)
