### ISSUE TITLE
Broken home page link on NPM

### ISSUE THREAD

**Issue by paulsmithkc** [immutable-js/immutable-js#1836]
### What happened

The home page link on NPM is broken. 
It should point to https://immutable-js.com/
But it still points to https://facebook.github.com/immutable-js

### How to reproduce

1. Search for immutable on npmjs.com or go directly to https://www.npmjs.com/package/immutable
2. Try to open home page link from sidebar

![image](https://user-images.githubusercontent.com/6501079/124401430-25899480-dcef-11eb-828b-d74b3505cf77.png)

**Comment by jdeniau** [comment]
Hi! We change the repository from Facebook to immutable-js.
I think it will be updated with the next RC to come.
