### ISSUE TITLE
sorting doesn't work on non primitives

### ISSUE THREAD

**Issue by uriva** [immutable-js/immutable-js#1871]
`List.of(List.of(2018,10), List.of(2018,5), List.of(2018, 11)).sort().toJS()`

gives this: 
`[ [ 2018, 10 ], [ 2018, 11 ], [ 2018, 5 ] ]`

I expected `[2018, 5]` or `[2018, 11]` to be first, which is not the case. Is this intended behaviour?

**Comment by jdeniau** [comment]
According to [the documentation] (https://immutable-js.com/docs/v4.0.0-rc.14/List/#sort())

> If a comparator is not provided, a default comparator uses < and >.

I think that array comparaison does not work as you would like in pure JS (I'm not on a computer so I did not test exactly). 
I think you should provide a comparator function in your case.

Please re-open if I'm wrong about JS comparaison.

**Comment by uriva** [comment]
in python this "default comparator" uses lexicographic ordering (for `tuple`).
this is very natural and very convenient and allows sorting per multiple elements.
i expected the built-in comparator here to do the same. if it uses the js `>` then it's just meaningless becasue these are objects.

so maybe this is a feature request?

**Comment by jdeniau** [comment]
I understand that a python-like comparison function might seems more logical, but we won't change default behavior, as it does stick with the JavaScript default.

I suggest you to either : 

#### implement a comparison function in your use case

```js
const l = List.of(
  List.of(2018,10),
  List.of(2018,5),
  List.of(2018, 11)
)

function lexicographicComparison(a, b) {
  // do comparison
}

l.sort(lexicographicComparison).toJS()
```

#### Use a custom object

In JavaScript you can use a custom object [that overrides `valueOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf#overriding_valueof_for_custom_objects) to compare

```js
function YearMonthTuple(year, month) {
  this.year = year;
  this.month = month;
}

YearMonthTuple.prototype.valueOf = function() {
  // basic month conversion, you may want to do better.
  return this.year * 12 + this.month;
};

const l = List.of(
  new YearMonthTuple(2018,10),
  new YearMonthTuple(2018,5),
  new YearMonthTuple(2018, 11)
)

l.sort().toJS()
```

**Comment by uriva** [comment]
I don't really understand this part:
> we won't change default behavior, as it does stick with the JavaScript default.

do you mean what js does for comparing `Object`s?
if so - how is that behaviour useful and why should we stick to it?

**Comment by comatory** [comment]
Because the library should behave as expected as far as idiomatic JS goes. You can use your own comparator to do what you want.

**Comment by uriva** [comment]
in js strings are compared lexicographically, and since immutable objects are more similar to primitives than mutable objects, i expected this comparator behaviour to be the default and was surprised that it doesn't work this way.

so for me it is "idiomatic" to compare them lexicographically.

so now that we established that "idiomaticity" is subjective, (reminds me of common use of the word "natural"), maybe we should discuss usefullness?

because it's completely useless (and please correct me if I'm wrong) to compare pointers, whereas it's prettty darn useful to compare immutable sequences lexicographically - one example is that you sort by multiple bits, controlling signifcance by order, e.g. `sortBy(juxt(predicate1, predicate2))`
