### ISSUE TITLE
Can't type empty Seq constructor 

### ISSUE THREAD

**Issue by pbadenski** [immutable-js/immutable-js#1876]
TS signature for empty Seq constructor doesn't allow manually setting generic type.

Is:
`function Seq(): Seq<unknown, unknown>;`

Should be:
`function Seq<K = unknown, V = unknown>(): Seq<K, V>;`

Same problem for `Seq.Keyed`, `Seq.Indexed` and `Seq.Set`.

Version: `4.0.0-rc.15`

**Comment by jdeniau** [comment]
Hi, 

Thank you for your bug report. 
Could you eventually open a PR with a test?
