### ISSUE TITLE
list.setIn([]) inserts empty array

### ISSUE THREAD

**Issue by justintim-es** [immutable-js/immutable-js#1904]
```
 offersLA: state.offersLA.setIn([
            action.payload!.index,
            'fixumDefences'
          ], List(action.payload!.liberDef)).setIn([
            action.payload!.index,
            'liberDefences'
          ], List(action.payload!.fixumDef))
        };
```
the payload has value but the list inside of the list stays empty
```"^4.0.0"```

**Comment by jdeniau** [comment]
Hi,

Can you provide a more reproducible example? It looks like you copy pasted a portion of your code.
The best example is to make the smallest possible code that contains your issue.

Thanks

**Comment by jdeniau** [comment]
Closing as no response were given since years.
