### ISSUE TITLE
Set.concat Not working as expected on String's

### ISSUE THREAD

**Issue by rodhoward** [immutable-js/immutable-js#1910]
When concatenating a new string Item into an existing set its treating the string as an array where as [].concat treats it as an item.

![Selection_051](https://user-images.githubusercontent.com/6284297/188338483-d34f1d49-a307-4efb-9ab0-99e46ad6db29.png)

I would expect and prefer it to treat the string as an item.

Regards
Rod

**Comment by jdeniau** [comment]
You are right that this is inconsistent.

For the record, I suggest you to use `.add` instead of `.concat`, you will have the expected result.

The concat method takes one or several iterables as argument. As a string is an iterable of char, it does work.
At first sight, technically, the Set implementation seems right and the List wrong here.

**Comment by rodhoward** [comment]
I think because javascript's array concat treats a string as a single item. e.g.
```
["one", "two"].concat("three")
(3) ['one', 'two', 'three']
```
Your better off following the list behavour in Set as well because its more intuitive.

**Comment by jdeniau** [comment]
You are right, and the immutable doc does explain this too !

> List.concat
> Returns a new List with **other values** or collections concatenated to this one.

> Set
> Returns a new Collection with other collections concatenated to this one.

So the List does handle passing values. We might update Set to be consistant with Javascript implementation

The line that test it is this line : 

If argument has iterator and is not a string, so take it, instead do convert it into an array

https://github.com/immutable-js/immutable-js/blob/803e8a94f86a13eee33a1ca876f8d5bc81d3196a/src/List.js#L145
