### ISSUE TITLE
createSerializableStateInvariantMiddleware for Record in React Redux TS

### ISSUE THREAD

**Issue by long76** [immutable-js/immutable-js#1911]
https://redux-toolkit.js.org/api/serializabilityMiddleware has example with `Immutable JS` `Iterable`. How create it for `Record`?

### What happened

console error
```js
react_devtools_backend.js:4026 A non-serializable value was detected in the state, in the path: `<root>`. Value: Record
```

### How to reproduce

put in react redux store `Record` and load page

**Comment by long76** [comment]
maybe better middleware for all immutable js types?

**Comment by jdeniau** [comment]
Hi, sorry for the delay.
Redux-toolkit uses immerjs by default.

You can see [here a discussion](https://github.com/reduxjs/redux-toolkit/discussions/3539#discussioncomment-7329720) to make it more "plugin compatible", but we are far from here.

On a personal point of view, I drop the migration ton RTK with immutable.

**Comment by long76** [comment]
I see, thanks!
