### ISSUE TITLE
4.2.0: partition missing in flow

### ISSUE THREAD

**Issue by Dagur** [immutable-js/immutable-js#1919]
### What happened

The new *partition* method is not included in the flow spec

**Comment by jdeniau** [comment]
Hi @Dagur .

If you are willing to implement this, I will merge it, but I do not know Flow at all, so I won't take the chance to break something ! (I struggle enough with the TypeScript definition file 😅 )

**Comment by Dagur** [comment]
I'm far from being an expert on flow but this seems to work

https://github.com/immutable-js/immutable-js/pull/1920

**Comment by jdeniau** [comment]
Fixed by #1920
