### ISSUE TITLE
Question: Wiki article for upgrading to v4

### ISSUE THREAD

**Issue by rajasegar** [immutable-js/immutable-js#1925]
Do we have a wiki article like this one for upgrading to v4?
https://github.com/immutable-js/immutable-js/wiki/Upgrading-to-Immutable-v3

Where can we find the changes related to v4 upgrade?

**Comment by jdeniau** [comment]
Hi,

You can look at the release page that explain the changes : https://github.com/immutable-js/immutable-js/releases/tag/v4.0.0

**Comment by bdurrer** [comment]
There is also a changelog page (it should contain the same information as the list of releases)
https://github.com/immutable-js/immutable-js/blob/main/CHANGELOG.md

**Comment by rajasegar** [comment]
@jdeniau @bdurrer Thanks folks 👍
