### ISSUE TITLE
Wrong typescript declarations for `.update()` method (continued)

### ISSUE THREAD

**Issue by cypherfunc** [immutable-js/immutable-js#1931]
### What happened
This is a continuation of [issue 1466](https://github.com/immutable-js/immutable-js/issues/1466).
In [1842](https://github.com/immutable-js/immutable-js/pull/1842), `| undefined` was added to the updater function's parameter type, but not the return type. As mentioned in a [comment](https://github.com/immutable-js/immutable-js/issues/1466#issuecomment-353705724) on that issue, the return type also needs to allow `undefined`. This is specifically needed for cases where no update is applied if the entry does not exist, or where the entry should be deleted.

e.g.
```
const myMap = Map<string, List<string>>();
const stillMyMap = myMap.update("noKey", ls => ls?.map(x => x + "blah"));
```
Since `myMap` doesn't have an entry for "noKey", `ls` is `undefined`, and thus the updater returns `undefined`.

### How to reproduce

Run Typescript type-checking on the above example, with `strictNullChecks` turned on. You will get an error like:
```
error TS2345: Argument of type '(ls: List<string>|undefined) => List<string>|undefined' is not assignable to parameter of type  '(ls: List<string>|undefined) => List<string>'.
  Type 'List<string>|undefined' is not assignable to type 'List<string>'.
    Type 'undefined' is not assignable to type 'List<string>'.
```

**Comment by jdeniau** [comment]
@cypherfunc Can you try to patch the immutable definition file in #1933 to see if it does fix your issue before I merge ?

**Comment by cypherfunc** [comment]
@jdeniau That's perfect, thanks so much! I didn't expect such a quick response.
