### ISSUE TITLE
Highlight inputs where `Set` can't maintain uniqueness

### ISSUE THREAD

**Issue by ornamentist** [immutable-js/immutable-js#1941]
Is it worthwhile to highlight in the documentation for `Set` constructors, situations where uniqueness of elements can't be maintained, for example:

```
const IJS = await import("immutable");

const s1 = new IJS.Set([[1], [1]])
console.log(s1.toArray())  // [ [ 1 ], [ 1 ] ], should be [[1]]

```

I'm guessing this is a result of JavaScript's approach to equality and identity of values. In these situations should we manually create a unique array of values first using something like `hash()` and `Map` for the set items? Although we'd need to do that for every constructive set operation:

```
const IJS = await import("immutable");

const s1 = new IJS.Set([[1], [1]])
const s2 = new IJS.Set([[1], [1]])
console.log(s1.union(s2).toArray()) // [ [ 1 ], [ 1 ], [ 1 ], [ 1 ] ]
```

**Comment by AldoMX** [comment]
This works for me:

```javascript
const IJS = await import("immutable");

const s1 = new IJS.Set([IJS.List([1]), IJS.List([1])])
const s2 = new IJS.Set([IJS.List([1]), IJS.List([1])])
console.log(s1.union(s2).toArray()) // [ [ 1 ] ]
```

**Comment by bdurrer** [comment]
`[] === [] //false`
` {} === {} // false`


Arrays (like objects) are never equal in standard JS., I would argue that it is one of the key point immutable collections solve. IMO AldoMX solution is the way to go

**Comment by ornamentist** [comment]
> This works for me:
> 
> ```js
> const IJS = await import("immutable");
> 
> const s1 = new IJS.Set([IJS.List([1]), IJS.List([1])])
> const s2 = new IJS.Set([IJS.List([1]), IJS.List([1])])
> console.log(s1.union(s2).toArray()) // [ [ 1 ] ]
> ```

This is pretty much what I ended up doing and seems to work well. I guess the constructor functions could take an optional `equal` parameter, but that's starting to get complicated.

**Comment by ornamentist** [comment]
> `[] === [] //false` ` {} === {} // false`
> 
> Arrays (like objects) are never equal in standard JS., I would argue that it is one of the key point immutable collections solve. IMO AldoMX solution is the way to go

Good point.
