### ISSUE TITLE
where is the doc of the v5?

### ISSUE THREAD

**Issue by sarahBuisson** [immutable-js/immutable-js#1995]
I use the beta of the v5 of immutable js ( in typescript) but I can't find the doc, where is it?

**Comment by jdeniau** [comment]
Hi, the v5 documentation is not available at, the moment, but you can, check out the changelog for now : 
There is nearly no breaking change on runtime, only for TS types

https://github.com/immutable-js/immutable-js/blob/5.x/CHANGELOG.md

V5 will be released soon (a few weeks I think). I still have some small stuff to do on TS file.

**Comment by bdurrer** [comment]
V5 docs are available on the website by now: https://immutable-js.com/docs/v5.0.0-rc.2/
