### ISSUE TITLE
using typescript instance  class

### ISSUE THREAD

**Issue by sarahBuisson** [immutable-js/immutable-js#1996]
When I use ImmutableJs  on the instance of a ts class, I didn"t get neither a record nor a FromJs
```

class A {
    constructor(public a: number) {
    }
}

console.log("A",fromJS(new A(2)));
```

Is it possible to use instance instead of structure?

**Comment by jdeniau** [comment]
I do not have a computer right now, but FromJS will return either a `List` or a `Map`.
In an object case, it will be converted to a `Map`, by iterating on each property.
You will probably have either a Map with `a` as key or an empty Map if the class `a` prop is not iterable.
