### ISSUE TITLE
Singleton `emptyList` is problematic

### ISSUE THREAD

**Issue by VirtuaBoza** [immutable-js/immutable-js#2003]
I just ran down a nasty bug related to this code below:

https://github.com/immutable-js/immutable-js/blob/493afba6ec17d9c999dc5a15ac80c71c6bdba1c3/src/List.js#L413

I did not realize that every time I was creating a new list with `List()`, I was getting the same _instance_ of `List`. This seems counterintuitive in a library based on the idea of immutability. 

Some code in the project was mutating an instance of an empty list which caused all subsequent newly minted lists to be non-empty. Obviously the code in my project was incorrect, but I came here to suggest _not_ using a singleton pattern here regardless.

**Comment by jdeniau** [comment]
Nice catch. A possible fix would be either to make the new list not mutable, or create a new list every time, or reset EMPTY_LIST if it has been mutated.

**Comment by bdurrer** [comment]
That's funny...In our project we made our own EMPTY_LIST to allow skipping React's "did something change" checks when consecutive calls returned nothing. 

I am a bit suprised that we seem to just have done that as a reaction to reading the code, because a test would obviously have caught that

**Comment by jdeniau** [comment]
@VirtuaBoza Can you share with us a reproductible example ?

I tried to implement https://github.com/immutable-js/immutable-js/pull/2004 but I am not able to reproduce your issue. I tested with `asMutable` and `withMutation` without success.

**Comment by VirtuaBoza** [comment]
> @VirtuaBoza Can you share with us a reproductible example ?
> 
> I tried to implement #2004 but I am not able to reproduce your issue. I tested with `asMutable` and `withMutation` without success.

The problematic code was as follows:
```
Object.assign(List(), newIds)
```
