### ISSUE TITLE
Typescript return type of sort/sortBy on non-Ordered Collections isn't accurate

### ISSUE THREAD

**Issue by cypherfunc** [immutable-js/immutable-js#2012]
### What happened

When calling `.sort()` or `.sortBy()` on non-"Ordered" Collections like Maps and Sets, the return type is the same as the original Collection, when it actually returns the "Ordered" version.

According to the docs:
https://github.com/immutable-js/immutable-js/blob/0c2d021552ee74022863f33ff3704f44c4862fde/type-definitions/immutable.d.ts#L4570-L4582

This matches the implementations:
https://github.com/immutable-js/immutable-js/blob/0c2d021552ee74022863f33ff3704f44c4862fde/src/Map.js#L112-L120
https://github.com/immutable-js/immutable-js/blob/0c2d021552ee74022863f33ff3704f44c4862fde/src/Set.js#L153-L161

However the TS types just use the inherited definitions from `interface Collection<K, V>`:
https://github.com/immutable-js/immutable-js/blob/0c2d021552ee74022863f33ff3704f44c4862fde/type-definitions/immutable.d.ts#L4589
https://github.com/immutable-js/immutable-js/blob/0c2d021552ee74022863f33ff3704f44c4862fde/type-definitions/immutable.d.ts#L4612-L4615

It's possible to monkey-patch the Map and Set interfaces like this:
```
declare module "immutable" {
    export interface Map<K, V> {
        sort(comparator?: Comparator<V>): OrderedMap<K, V>;
        sortBy<C>(
            comparatorValueMapper: (value: V, key: K, iter: this) => C,
            comparator?: (valueA: C, valueB: C) => number
        ): OrderedMap<K, V>;
    }

    export interface Set<T> {
        sort(comparator?: Comparator<T>): OrderedSet<T>;
        sortBy<C>(
            comparatorValueMapper: (value: T, key: T, iter: this) => C,
            comparator?: (valueA: C, valueB: C) => number
        ): OrderedSet<T>;
    }
}
```
However, I don't know enough to recommend that as the real fix. This issue probably also affects some other types besides just Map and Set, and it might be better to add the accurate definitions on one of the abstract types, or some other interface. 🤷 

### How to reproduce

Call `.sort()` or `.sortBy()` on a Map or Set and look at the returned type.

**Comment by jdeniau** [comment]
Hi,

Thanks for the report. I think that the fix should be easy in the TS definition file.
We should override the function definition in Map, Set etc. interface, just like you did in your example.

If you are willing to open a PR, that would be great, otherwise I will try to implement this when I'm back home.
