### ISSUE TITLE
Migration Guide from v3 to v4

### ISSUE THREAD

**Issue by haron-IV** [immutable-js/immutable-js#2018]
Hi community!
I'm looking for some guide, or just differences list of v3 to v4.
Really hard to find anything about migrating from v3 to v4 or later.
Anyone have upgraded it and can share some resources?

**Comment by Methuselah96** [comment]
Check out [the release notes for v4.0.0](https://github.com/immutable-js/immutable-js/releases/tag/v4.0.0)

**Comment by jdeniau** [comment]
Closing as the release note should contain all the informations you need 🤞
