### ISSUE TITLE
🏁 Race of Sloths: The Open Source Developer Challenge is about to start

### ISSUE THREAD

**Issue by akorchyn** [immutable-js/immutable-js#2023]
As a team of Rust developers from [Race of Sloths](https://race-of-sloths.com/),  we recognized this repo to be highly valuable in the open-source movement.

Race of Sloth makes the open-source contributions more fun and rewarding.

* This issue is an invitation to check how Race of Sloths works
* To accept the invitation, comment @race-of-sloths accept
* Once the invitation is accepted, your contributors are eligible participate in the Race
* Contributors just need to mention @race-of-sloths in their PR within your normal contribution flow
* We invite you for collaboration and making open source development more engaging together!

**Comment by jdeniau** [comment]
Hi,

The fact that you try to gamify pull request creation might be interesting, but I do no want:
- useless PR just to gain "points",
- comments to / from your bot where PR comments is gold to understand it and know what's happening in the PR,
- distribute point to contributors. I'm a maintainer, not a game master (in this context at least).
